server:
  port: ${SERVER_PORT}
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: "pos-v1"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
